# FirstSettingRegion is Default,
# SecondSettingRegion "IncludeGlobalEvents" is False

AWSTemplateFormatVersion: 2010-09-09
Description: Enable AWS CloudTrail. This template creates a CloudTrail trail, an Amazon S3 bucket where logs are published, and an Amazon SNS topic where notifications are sent.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Trail Configuration
        Parameters:
          - EnableLogFileValidation
          - IncludeGlobalEvents
          - MultiRegion
    ParameterLabels:
      EnableLogFileValidation:
        default: Enable log file validation
      IncludeGlobalEvents:
        default: Include global service events
      MultiRegion:
        default: Is this a multi-region trail

Parameters:
  EnableLogFileValidation:
    Type: String
    Default: False
    Description: Indicates whether CloudTrail validates the integrity of log files.
    AllowedValues:
      - True
      - False

  IncludeGlobalEvents:
    Type: String
    Default: True
    Description: Indicates whether the trail is publishing events from global services, such as IAM, to the log files.
    AllowedValues:
      - True
      - False

  MultiRegion:
    Type: String
    Default: True
    Description: Indicates whether the CloudTrail trail is created in the region in which you create the stack (false) or in all regions (true).
    AllowedValues:
      - True
      - False

Conditions:
  IsMultiRegion: !Equals
    - !Ref MultiRegion
    - True

Resources:
  TrailBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: "CloudtrailBucket"
          Status: Enabled
          ExpirationInDays: 1095
          Transitions:
            - StorageClass: DEEP_ARCHIVE
              TransitionInDays: 0

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSTrailBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${TrailBucket}"
          - Sid: AWSTrailBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:${AWS::Partition}:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*"
          - Sid: AWSTrailBucketSecureTransport
            Action:
              - s3:*
            Effect: Deny
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${TrailBucket}"
              - !Sub "arn:${AWS::Partition}:s3:::${TrailBucket}/*"
            Principal: "*"
            Condition:
              Bool:
                aws:SecureTransport:
                  false

  Trail:
    DependsOn:
      - TrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref TrailBucket
      IsLogging: true
      EnableLogFileValidation: !Ref EnableLogFileValidation
      IncludeGlobalServiceEvents: !If
        - IsMultiRegion
        - true
        - !Ref IncludeGlobalEvents
      IsMultiRegionTrail: !Ref MultiRegion
