# FirstSettingRegion is Default,
# SecondSettingRegion "IncludeGlobalResourceTypes" is False

AWSTemplateFormatVersion: "2010-09-09"
Description: Enable AWS Config

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Recorder Configuration
        Parameters:
          - AllSupported
          - IncludeGlobalResourceTypes
          - ResourceTypes

Parameters:
  AllSupported:
    Type: String
    Default: True
    Description: All Config Records Or Not Or NULL（RecorderRecordingStrategy = EXCLUSION_BY_RESOURCE_TYPES)
    AllowedValues:
      - ''
      - True
      - False

  IncludeGlobalResourceTypes:
    Type: String
    Default: True
    Description: Include Grobal Resorce. if AllSupported is "", This is AWS::NoValue
    AllowedValues:
      - True
      - False

  RecordResourceTypes:
    Type: List<String>
    Description: A list of valid AWS resource types to include in this recording group, such as AWS::EC2::Instance or AWS::CloudTrail::Trail.
    Default: AWS::EC2::Instance, AWS::CloudTrail::Trail

  RecorderRecordingStrategy:
    Type: String
    Description: The recording strategy for the configuration recorder.
    Default: ''
    AllowedValues:
      - ''
      - ALL_SUPPORTED_RESOURCE_TYPES
      - INCLUSION_BY_RESOURCE_TYPES
      - EXCLUSION_BY_RESOURCE_TYPES

  EXCLUSIONResourceTypes:
    Type: List<String>
    Description: A list of valid AWS EXCLUSION resource types to include in this recording group, such as AWS::EC2::VPC
    Default: ''

Conditions:
  IsAllSupported: !Or 
    - !Equals [!Ref AllSupported,True]
    - !Equals [!Ref AllSupported,'']

  IsEmptyAllSupported: !Equals
    - !Ref AllSupported
    - ''

  IsRecorderRecordingStrategy: !Not
    - !Equals [!Ref RecorderRecordingStrategy, EXCLUSION_BY_RESOURCE_TYPES]

  IsEmptyRecorderRecordingStrategy: !Equals
    - !Ref RecorderRecordingStrategy
    - ''

Resources:
  ConfigBucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - Id: "AWSConfigS3-life_cycle"
          Status: Enabled
          ExpirationInDays: 40
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource:
              - !Sub "arn:aws:s3:::${ConfigBucket}"
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: s3:PutObject
            Resource:
              - !Sub "arn:aws:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*"

  ConfigRecorderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    DependsOn:
       ConfigBucketPolicy
    Properties:
      Name: "default"
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: !If
          - IsEmptyAllSupported
          - !Ref AWS::NoValue
          - !Ref AllSupported
        IncludeGlobalResourceTypes: !If
          - IsEmptyAllSupported
          - !Ref AWS::NoValue
          - !Ref IncludeGlobalResourceTypes
        ResourceTypes: !If
          - IsAllSupported
          - !Ref AWS::NoValue
          - !Ref RecordResourceTypes
        ExclusionByResourceTypes: !If
          - IsRecorderRecordingStrategy
          - !Ref AWS::NoValue
          - ResourceTypes:
              !Ref EXCLUSIONResourceTypes
        RecordingStrategy: !If
          - IsEmptyRecorderRecordingStrategy
          - !Ref AWS::NoValue
          - UseOnly: 
              !Ref RecorderRecordingStrategy

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn:
       ConfigBucketPolicy
    Properties:
      Name: "default"
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: TwentyFour_Hours
      S3BucketName: !Ref ConfigBucket
