AWSTemplateFormatVersion: 2010-09-09
Description: Security Hub

Resources:
  SecurityHub:
    Type: 'AWS::SecurityHub::Hub'
    Properties:
      AutoEnableControls: false
      EnableDefaultStandards: false
      ControlFindingGenerator: STANDARD_CONTROL

  Standard:
    Type: 'AWS::SecurityHub::Standard'
    DependsOn: SecurityHub
    Properties:
      StandardsArn: !Sub 'arn:${AWS::Partition}:securityhub:${AWS::Region}::standards/aws-foundational-security-best-practices/v/1.0.0'
